version: '2'
services:
  zk-1:
    image: 801351377084.dkr.ecr.us-west-1.amazonaws.com/zookeeper-exhibitor
    ports:
      - 2181
    labels:
      avanti.service.count: "1"
  kafka-1:
    image: 801351377084.dkr.ecr.us-west-1.amazonaws.com/dte-splunk-sink
    environment:
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 120000
    ports:
      - 9092
      - 8083
    labels:
      avanti.service.count: "1"
    depends_on:
      - zk-1
  mq-monitor:
    build: .
    ports:
       - 9023:8000
    environment:
      SERVICE_NAME: mq-monitor
      CLUSTER_NAME: local
    labels:
      avanti.service.count: "1"
    depends_on:
      - kafka-1
